# This is the version of the Kubernetes API that we're using for this resource.
# "v1" is the version that is used for core Kubernetes resources, including Services.
apiVersion: v1

# A Service in Kubernetes is a way to expose an application, Deployment, ReplicaSet, StatefulSet, or Pod as a network service.
kind: Service

metadata:
  # The unique name for this Service within the Kubernetes namespace.
  # This is how other resources or users can refer to this Service.
  name: mongodb-service

spec: # The specification of the desired behavior of the Service.
  # The ports field is used to define the ports that are associated with the Service.
  ports:
    # This port configuration tells Kubernetes that the Service should be reachable at port 27017.
    # The port number matches the MongoDB default port.
    - port: 27017

  # The selector determines which pods are targeted by this Service.
  # Any pod with labels matching the selector will be reachable through this Service.
  # In this case, it targets pods that have the label "app" with the value "mongodb".
  selector:
    app: mongodb
