# This is the version of the Kubernetes API that we're using for this resource.
# "v1" is commonly used for core Kubernetes resources, including PersistentVolumeClaim.
apiVersion: v1

# A PersistentVolumeClaim (PVC) is a request for storage by a user.
# It's similar to a Pod: Pods consume node resources, and PVCs consume PersistentVolume resources.
kind: PersistentVolumeClaim

metadata:
  # The unique name for this PersistentVolumeClaim within the Kubernetes namespace.
  # This is how other resources or users can refer to this PVC.
  name: mongodb-pvc

spec: # The specification of the desired behavior of the PersistentVolumeClaim.
  # The storageClassName specifies which StorageClass this PVC should be associated with.
  # "manual" is used here, matching our earlier defined PersistentVolume's storage class.
  storageClassName: manual

  # Defines the mode of access for the PersistentVolumeClaim.
  accessModes:
    # "ReadWriteOnce" means the volume can be mounted as read-write by a single node.
    - ReadWriteOnce

  # Here, you specify the storage requirements of the PVC.
  resources:
    # This is the amount of storage you're requesting from the cluster for this PVC.
    requests:
      # In this example, you're requesting 1 GiB (Gigabyte) of storage.
      storage: 1Gi
