version: "3"

services:
  auth-service:
    build:
      context: ./backend/services/auth-Service/
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - AUTH_CONNECTION=mongodb://api_mongo:27017/service-auth
      - JWT_SECRET=secret
    networks:
      - chat-app-network
    depends_on:
      - api_mongo

  user-service:
    build:
      context: ./backend/services/user-Service/
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - USER_CONNECTION=mongodb://api_mongo:27017/service-user
      - JWT_SECRET=secret
    networks:
      - chat-app-network
    depends_on:
      - api_mongo

  conversation-service:
    build:
      context: ./backend/services/conversation-Service/
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - CONVERSATION_CONNECTION=mongodb://api_mongo:27017/service-conversation
      - JWT_SECRET=secret
    networks:
      - chat-app-network
    depends_on:
      - api_mongo

  graphql-server:
    build:
      context: ./backend/server/
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - JWT_SECRET=secret
      - AUTH_SERVICE_CONNECTION=http://auth-service:3001/auth
      - USER_SERVICE_CONNECTION=http://user-service:3002/user
    networks:
      - chat-app-network
    depends_on:
      - auth-service
      - user-service
      - conversation-service

  api_mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - chat-app-network

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - chat-app-network
    depends_on:
      - graphql-server

networks:
  chat-app-network:
    driver: bridge

volumes:
  mongo-data:
